name: CI/CD

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  pipeline:
    uses: whittakertech/.github/.github/workflows/master-ci.yml@main
    with:
      docs_enabled: false
    secrets: inherit
